# Generated by Django 2.2.3 on 2019-09-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('staff_name', models.CharField(max_length=20)),
                ('staff_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('staff_department', models.CharField(max_length=15)),
                ('r_equipment', models.CharField(choices=[('Mon', 'Monitor'), ('CPU', 'Central Processing Unit'), ('KB', 'Keyboard'), ('Mou', 'Mouse')], max_length=3)),
            ],
            options={
                'ordering': ('staff_number',),
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8)),
                ('mac_address', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('assigned_to', models.CharField(default='Not assigned', max_length=15)),
                ('department', models.CharField(default='store', max_length=15)),
                ('staffrequest', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='inventory.StaffRequest')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
