# Generated by Django 2.2.3 on 2019-09-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrequest',
            name='r_equipment',
            field=models.CharField(choices=[('Mon', 'Monitor'), ('CPU', 'Central Processing Unit'), ('KB', 'Keyboard'), ('Mou', 'Mouse')], default='comp', max_length=3),
        ),
    ]
